/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_minisql_util_BTree */

#ifndef _Included_com_minisql_util_BTree
#define _Included_com_minisql_util_BTree
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_minisql_util_BTree
 * Method:    nativeCreate
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_com_minisql_util_BTree_nativeCreate
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_minisql_util_BTree
 * Method:    nativeDestroy
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_minisql_util_BTree_nativeDestroy
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_minisql_util_BTree
 * Method:    nativePrint
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_minisql_util_BTree_nativePrint
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_minisql_util_BTree
 * Method:    nativeInsert
 * Signature: (JIJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_minisql_util_BTree_nativeInsert__JIJ
  (JNIEnv *, jobject, jlong, jint, jlong);

/*
 * Class:     com_minisql_util_BTree
 * Method:    nativeInsert
 * Signature: (JDJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_minisql_util_BTree_nativeInsert__JDJ
  (JNIEnv *, jobject, jlong, jdouble, jlong);

/*
 * Class:     com_minisql_util_BTree
 * Method:    nativeInsert
 * Signature: (JLjava/lang/String;J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_minisql_util_BTree_nativeInsert__JLjava_lang_String_2J
  (JNIEnv *, jobject, jlong, jstring, jlong);

/*
 * Class:     com_minisql_util_BTree
 * Method:    nativeDelete
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_minisql_util_BTree_nativeDelete__JI
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_minisql_util_BTree
 * Method:    nativeDelete
 * Signature: (JD)Z
 */
JNIEXPORT jboolean JNICALL Java_com_minisql_util_BTree_nativeDelete__JD
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     com_minisql_util_BTree
 * Method:    nativeDelete
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_minisql_util_BTree_nativeDelete__JLjava_lang_String_2
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_minisql_util_BTree
 * Method:    nativeSearch
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_com_minisql_util_BTree_nativeSearch__JI
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_minisql_util_BTree
 * Method:    nativeSearch
 * Signature: (JD)J
 */
JNIEXPORT jlong JNICALL Java_com_minisql_util_BTree_nativeSearch__JD
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     com_minisql_util_BTree
 * Method:    nativeSearch
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_minisql_util_BTree_nativeSearch__JLjava_lang_String_2
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_minisql_util_BTree
 * Method:    nativeRetrieve
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_com_minisql_util_BTree_nativeRetrieve__JI
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_minisql_util_BTree
 * Method:    nativeRetrieve
 * Signature: (JD)J
 */
JNIEXPORT jlong JNICALL Java_com_minisql_util_BTree_nativeRetrieve__JD
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     com_minisql_util_BTree
 * Method:    nativeRetrieve
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_minisql_util_BTree_nativeRetrieve__JLjava_lang_String_2
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_minisql_util_BTree
 * Method:    nativeUpdate
 * Signature: (JII)Z
 */
JNIEXPORT jboolean JNICALL Java_com_minisql_util_BTree_nativeUpdate__JII
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     com_minisql_util_BTree
 * Method:    nativeUpdate
 * Signature: (JDD)Z
 */
JNIEXPORT jboolean JNICALL Java_com_minisql_util_BTree_nativeUpdate__JDD
  (JNIEnv *, jobject, jlong, jdouble, jdouble);

/*
 * Class:     com_minisql_util_BTree
 * Method:    nativeUpdate
 * Signature: (JLjava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_minisql_util_BTree_nativeUpdate__JLjava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jlong, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
